<script lang="ts">
	import './style.css';
	import ExpressMap from '../../components/ExpressMap.svelte';

	let promise = handleFetchEvents();

	async function handleFetchEvents() {
		let myHeaders = new Headers();
		myHeaders.append('pragma', 'no-cache');
		myHeaders.append('cache-control', 'no-cache');

		var fetchMeta = {
			method: 'GET',
			headers: myHeaders
		};
		const response = await fetch(
			'https://corsproxy.io//?https://leboeuflasing.ddns.net/uaEvents.json',
			fetchMeta
		);
		return await response.json();
	}
</script>

<svelte:head>
	<title>Current Events</title>
	<meta
		name="description"
		content="The current events of the UA Nasa Robotics Mining Team. See events, locations, times, and schedules."
	/>
	<meta
		name="keywords"
		content="NASA, Robotic Mining Competition, Lunabotics, Artemis, Moon to Mars, event, live, schedule, meet, in-person, calender"
	/>
	<meta name="author" content="uA NASA Robotic Mining Competition Team" />
</svelte:head>

<div class="text-column">
	<h1>Upcoming Events</h1>
	<p>
		Here is an live-updated calender of events Akron RMC Robotics will be attending. Come join us at
		these events and meet the team!
	</p>
	<div class="calenderContent">
		{#await promise}
			<p>Loading...</p>
		{:then events}
			{#if events.length <= 0}
				<div class="eventCard"><p>There are no upcoming events at this time.</p></div>
			{:else}
				{#each events as event}
					<div class="eventCard">
						{#if event.event_image_url && event.event_image_url.length > 0}
							<div class="eventImageDiv">
								<img src={event.event_image_url} alt="Event Thumbnail" class="eventImg" />
							</div>
						{:else}
							<!-- No image -->
						{/if}

						<div class="eventText">
							<h2>{event.event_name}</h2>
							<hr class="bar" />
							<p>
								{new Date(parseInt(event.event_date) * 1000).toDateString()}
								{new Date(parseInt(event.event_date) * 1000).toLocaleTimeString()}
							</p>
							<p>{event.event_location}</p>
							<p>{event.event_description}</p>
							<div class="attendanceMessage">
								<p>
									<sub>
										{#if event.event_required === '1'}
											<b>This event is required for members to attend.*</b>
										{:else}
											This event is not required for members to attend.*
										{/if}
									</sub>
								</p>
							</div>
						</div>
					</div>
				{/each}
				<div class="asteriskCard">
					<p>*Automatically generated by EventBot from context. May be inaccurate.</p>
				</div>
			{/if}
		{:catch error}
			<div class="eventCard">
				<p>There was an error loading the events. Please try again later.</p>
				<br /><button on:click={window.location.reload}>Refresh</button>
			</div>
		{/await}
	</div>

	<h2>Want to join the group?</h2>
	<p>
		All sub-team meetings and general meetings are held in the campus building known as the Express
		Building.
	</p>
	<ExpressMap />
</div>
