<script lang="ts">
	import './style.css';

	let promise = handleFetchEvents();

	async function handleFetchEvents() {
		const response = await fetch(
			'https://corsproxy.io//?https://leboeuflasing.ddns.net/uaEvents.json',
			{ method: 'GET' }
		);
		return await response.json();
	}
</script>

<svelte:head>
	<title>Current Events</title>
	<meta name="description" content="The current events happening for UA Robotics." />
</svelte:head>

<div class="text-column">
	<h1>Upcoming Events</h1>
	<p>
		Here is an live-updated calender of events Akron RMC Robotics will be attending. Come join us at
		these events and meet the team!
	</p>
	<div class="calender-content">
		{#await promise}
			<p>Loading...</p>
		{:then events}
			{#if events.length <= 0}
				<div class="eventCard"><p>There are no upcoming events at this time.</p></div>
			{:else}
				{#each events as event}
					<div class="eventCard">
						<div class="eventText">
							<h2>{event.event_name}</h2>
							<hr class="bar" />
							<p>
								{new Date(parseInt(event.event_date) * 1000).toDateString()}
								{new Date(parseInt(event.event_date) * 1000).toLocaleTimeString()}
							</p>
							<p>{event.event_location}</p>
							<p>{event.event_description}</p>
							<sub>
								{#if event.event_required === '1'}
									<b>This event is required for members to attend.*</b>
								{:else}
									This event is not required for members to attend.*
								{/if}
							</sub>
						</div>
						<div class="eventImageDiv">
							{#if event.event_image_url && event.event_image_url.length > 0}
								<img src={event.event_image_url} alt="Event Thumbnail" class="eventImg" />
							{:else}
								<img src="/src/lib/images/logo.png" alt="Event Thumbnail" class="eventImg" />
							{/if}
						</div>
					</div>
				{/each}
				<p>*Automatically generated by EventBot from context. May be inaccurate.</p>
			{/if}
		{:catch error}
			<div class="eventCard">
				<p>There was an error loading the events. Please try again later.</p>
				<br /><button on:click={window.location.reload}>Refresh</button>
			</div>
		{/await}
	</div>
</div>
