# This workflow will build and deploy the svelte website onto a hosting server

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'archive/**'

jobs:
    build-and-run:
     runs-on: self-hosted
     steps:
      - name: stop webserver
        run: sudo -n /var/www/svelte-stop.sh
            
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rm old code
        run: rm -rf /var/www/svelte/{*,.*}

      - name: mv in new code
        run: mv ./* /var/www/svelte/

      #- name: Use Node.js 20.x
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: '20.x'

      - name: restart node service
        run: /var/www/svelte-start.sh
    
